import { useCallback, useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import type { DbClient } from './lib/api'
import { addInventoryEntry, archiveProduct, createCategory, getStockByProduct, reverseTransaction, saveProduct, updateStall } from './lib/api'
import { getDashboardMetrics } from './lib/dashboard'
import { downloadCsv } from './lib/export'
import type { Product, WorkspaceData } from './lib/types'
import { Badge, Button, EmptyState, Input, Notice, Panel, Select, Table, TableCell, TableHead, Textarea } from './components/ui'

const peso = new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' })
const dateTime = new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium', timeStyle: 'short' })

export type ScreenProps = {
  client: DbClient
  data: WorkspaceData
  onRefresh: () => Promise<void>
  onError: (message: string) => void
}

function getErrorMessage(error: unknown) {
  return error instanceof Error ? error.message : 'The operation could not be completed.'
}

export function OverviewScreen({ data, onNavigate }: ScreenProps & { onNavigate: (view: string) => void }) {
  const today = new Date().toISOString().slice(0, 10)
  const metrics = getDashboardMetrics(data.products, data.inventory, data.transactions, today)
  const stock = metrics.stock
  const lowStock = data.products.filter((product) => metrics.lowStock.includes(product.id))

  const cards = [
    { label: 'Sales today', value: peso.format(metrics.sales), detail: `${metrics.completedSales} completed sale${metrics.completedSales === 1 ? '' : 's'}`, action: () => onNavigate('reports') },
    { label: 'Low-stock items', value: String(lowStock.length), detail: lowStock.length ? 'Review stock levels' : 'Everything is above threshold', action: () => onNavigate('adjustments') },
    { label: 'Active products', value: String(data.products.filter((product) => product.is_sellable).length), detail: `${data.products.length} total catalog items`, action: () => onNavigate('products') },
    { label: 'Transactions', value: String(data.transactions.length), detail: 'Latest 1,000 records loaded', action: () => onNavigate('transactions') },
  ]

  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card) => <button key={card.label} className="rounded-2xl border border-[#eadcff] bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-[#caa8ff]" onClick={card.action}><p className="text-sm text-slate-500">{card.label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{card.value}</p><p className="mt-1 text-xs text-slate-400">{card.detail}</p></button>)}</div><div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><Panel title="Stock watchlist" description="Products at or below their configured threshold."><Table><TableHead><th className="px-3 py-3">Product</th><th className="px-3 py-3">On hand</th><th className="px-3 py-3">Threshold</th><th className="px-3 py-3">Status</th></TableHead><tbody>{lowStock.slice(0, 8).map((product) => { const onHand = stock[product.id] ?? 0; return <tr key={product.id} className="border-b border-slate-100"><TableCell><p className="font-medium">{product.name}</p><p className="text-xs text-slate-400">{product.sku}</p></TableCell><TableCell>{onHand.toLocaleString()} {product.unit}</TableCell><TableCell>{product.low_stock_threshold.toLocaleString()} {product.unit}</TableCell><TableCell><Badge tone={onHand <= 0 ? 'danger' : 'warning'}>{onHand <= 0 ? 'Out of stock' : 'Low stock'}</Badge></TableCell></tr> })}</tbody></Table>{lowStock.length === 0 && <EmptyState title="No stock alerts" description="All active products are above their configured thresholds." />}</Panel><Panel title="Quick actions" description="Common manager operations."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{[['Receive stock', 'receiving'], ['Adjust inventory', 'adjustments'], ['Edit prices', 'pricing'], ['Download sales report', 'reports']].map(([label, view]) => <Button key={view} variant="secondary" className="text-left" onClick={() => onNavigate(view)}>{label}</Button>)}</div></Panel></div></div>
}

export function StallScreen({ client, data, onRefresh, onError }: ScreenProps) {
  const stall = data.stall
  const [name, setName] = useState(stall?.name ?? '')
  const [code, setCode] = useState(stall?.code ?? '')
  const [message, setMessage] = useState('')
  const [saving, setSaving] = useState(false)
  async function submit(event: FormEvent) {
    event.preventDefault(); setMessage('')
    if (!stall || name.trim().length < 2 || code.trim().length < 2) { setMessage('Enter a stall name and code with at least 2 characters.'); return }
    setSaving(true)
    try { await updateStall(client, stall.id, { name: name.trim(), code: code.trim().toUpperCase() }); setMessage('Stall settings saved.'); await onRefresh() } catch (error) { onError(getErrorMessage(error)) } finally { setSaving(false) }
  }
  return <Panel title="Stall management" description="Keep the manager-facing stall identity and sync code accurate.">{!stall ? <EmptyState title="No stall found" description="Create the initial stall in Supabase before using the dashboard." /> : <form className="max-w-xl space-y-4" onSubmit={submit}><Input label="Stall name" value={name} onChange={(event) => setName(event.target.value)} required /><Input label="Stall code" hint="Used when identifying the stall during setup" value={code} onChange={(event) => setCode(event.target.value)} required /><div className="flex items-center gap-3"><Button disabled={saving}>{saving ? 'Saving…' : 'Save stall settings'}</Button>{message && <Notice tone="success">{message}</Notice>}</div></form>}</Panel>
}

const emptyProduct = { name: '', unit: 'piece', category_id: '', sale_price: '0', cost_price: '0', low_stock_threshold: '0', pack_size: '1', conversion_rate: '1', is_sellable: true }
type ProductFormValues = typeof emptyProduct

function ProductFormFields({ form, setField, categories }: { form: ProductFormValues; setField: (field: keyof ProductFormValues, value: string | boolean) => void; categories: WorkspaceData['categories'] }) {
  return <><Input label="Product name" value={form.name} onChange={(event) => setField('name', event.target.value)} required autoFocus /><p className="rounded-xl border border-[#eadcff] bg-[#fbf7ff] px-3 py-2 text-sm text-[#4b2a7a]"><span className="font-semibold">SKU:</span> Generated automatically when you save this product.</p><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Input label="Unit" value={form.unit} onChange={(event) => setField('unit', event.target.value)} required /><Select label="Category" value={form.category_id} onChange={(event) => setField('category_id', event.target.value)}><option value="">Uncategorized</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</Select></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Input label="Sale price" type="number" min="0" step="0.01" value={form.sale_price} onChange={(event) => setField('sale_price', event.target.value)} /><Input label="Cost price" type="number" min="0" step="0.01" value={form.cost_price} onChange={(event) => setField('cost_price', event.target.value)} /></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Input label="Low-stock threshold" type="number" min="0" step="0.001" value={form.low_stock_threshold} onChange={(event) => setField('low_stock_threshold', event.target.value)} /><Input label="Pack size" type="number" min="0.001" step="0.001" value={form.pack_size} onChange={(event) => setField('pack_size', event.target.value)} /></div><Input label="Conversion rate" hint="Usable units per pack" type="number" min="0.001" step="0.001" value={form.conversion_rate} onChange={(event) => setField('conversion_rate', event.target.value)} /><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={form.is_sellable} onChange={(event) => setField('is_sellable', event.target.checked)} /> Available for sale</label></>
}

export function ProductsScreen({ client, data, onRefresh, onError }: ScreenProps) {
  const [form, setForm] = useState(emptyProduct)
  const [editingId, setEditingId] = useState<string>()
  const [productModalOpen, setProductModalOpen] = useState(false)
  const [search, setSearch] = useState('')
  const [message, setMessage] = useState('')
  const [categoryName, setCategoryName] = useState('')
  const [saving, setSaving] = useState(false)
  const stock = getStockByProduct(data.inventory)
  const filtered = data.products.filter((product) => `${product.name} ${product.sku}`.toLowerCase().includes(search.toLowerCase()))
  function setField(field: keyof typeof emptyProduct, value: string | boolean) { setForm((current) => ({ ...current, [field]: value })) }
  function openAddProduct() { setEditingId(undefined); setForm(emptyProduct); setMessage(''); setProductModalOpen(true) }
  function edit(product: Product) { setEditingId(product.id); setForm({ name: product.name, unit: product.unit, category_id: product.category_id ?? '', sale_price: String(product.sale_price), cost_price: String(product.cost_price), low_stock_threshold: String(product.low_stock_threshold), pack_size: String(product.pack_size), conversion_rate: String(product.conversion_rate), is_sellable: product.is_sellable }); setMessage(''); setProductModalOpen(true) }
  const closeProductModal = useCallback(() => { if (saving) return; setProductModalOpen(false); setEditingId(undefined); setForm(emptyProduct); setMessage('') }, [saving])
  async function submit(event: FormEvent) {
    event.preventDefault(); setMessage('')
    const values = { ...form, name: form.name.trim(), unit: form.unit.trim() }
    const numbers = ['sale_price', 'cost_price', 'low_stock_threshold', 'pack_size', 'conversion_rate'].map((field) => Number(form[field as keyof typeof form]))
    if (!values.name || !values.unit || numbers.some((value) => !Number.isFinite(value) || value < 0) || numbers[3] <= 0 || numbers[4] <= 0) { setMessage('Complete all product fields with valid non-negative values. Pack size and conversion rate must be greater than zero.'); return }
    setSaving(true)
    try { await saveProduct(client, { stall_id: data.stall?.id ?? '', category_id: values.category_id || null, name: values.name, unit: values.unit, sale_price: numbers[0], cost_price: numbers[1], low_stock_threshold: numbers[2], pack_size: numbers[3], conversion_rate: numbers[4], is_sellable: form.is_sellable }, editingId); await onRefresh(); closeProductModal() } catch (error) { onError(getErrorMessage(error)) } finally { setSaving(false) }
  }
  async function addNewCategory(event: FormEvent) { event.preventDefault(); if (!categoryName.trim() || !data.stall) return; try { await createCategory(client, { stall_id: data.stall.id, name: categoryName.trim(), sort_order: data.categories.length }); setCategoryName(''); await onRefresh() } catch (error) { onError(getErrorMessage(error)) } }
  async function archive(product: Product) { if (!window.confirm(`Archive ${product.name}? It will no longer be sellable.`)) return; try { await archiveProduct(client, product.id); await onRefresh() } catch (error) { onError(getErrorMessage(error)) } }
  useEffect(() => {
    if (!productModalOpen) return
    const closeOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') closeProductModal() }
    document.addEventListener('keydown', closeOnEscape)
    document.body.style.overflow = 'hidden'
    return () => { document.removeEventListener('keydown', closeOnEscape); document.body.style.overflow = '' }
  }, [productModalOpen, closeProductModal])
  return <><Panel title="Product catalog" description="Manage menu items, packaging, prices, thresholds, and conversions." action={<div className="flex flex-col gap-2 sm:flex-row"><Input aria-label="Search products" placeholder="Search name or SKU" value={search} onChange={(event) => setSearch(event.target.value)} /><Button className="shrink-0" onClick={openAddProduct}>Add product</Button></div>}>
    {filtered.length === 0 ? <EmptyState title="No products found" description={search ? 'Try a different search.' : 'Add your first product to begin building the catalog.'} /> : <Table><TableHead><th className="px-3 py-3">Product</th><th className="px-3 py-3">Price</th><th className="px-3 py-3">On hand</th><th className="px-3 py-3">Status</th><th className="px-3 py-3" /></TableHead><tbody>{filtered.map((product) => { const onHand = stock[product.id] ?? 0; return <tr key={product.id} className="border-b border-slate-100"><TableCell><p className="font-medium">{product.name}</p><p className="text-xs text-slate-400">{product.sku} · {product.unit}</p></TableCell><TableCell>{peso.format(product.sale_price)}</TableCell><TableCell>{onHand.toLocaleString()}</TableCell><TableCell><Badge tone={!product.is_sellable ? 'neutral' : onHand <= product.low_stock_threshold ? 'warning' : 'success'}>{!product.is_sellable ? 'Archived' : onHand <= product.low_stock_threshold ? 'Low stock' : 'Active'}</Badge></TableCell><TableCell><div className="flex gap-2"><Button variant="ghost" onClick={() => edit(product)}>Edit</Button>{product.is_sellable && <Button variant="danger" onClick={() => void archive(product)}>Archive</Button>}</div></TableCell></tr> })}</tbody></Table>}
  </Panel>{productModalOpen && <div className="fixed inset-0 z-50 flex items-end bg-[#18002f]/55 p-0 backdrop-blur-[2px] sm:items-center sm:justify-center sm:p-6" onMouseDown={(event) => { if (event.target === event.currentTarget) closeProductModal() }}><section aria-labelledby="product-modal-title" aria-modal="true" className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl bg-[#fffdf8] shadow-2xl sm:max-w-2xl sm:rounded-3xl" role="dialog"><div className="sticky top-0 flex items-start justify-between gap-4 border-b border-[#eadcff] bg-[#fffdf8]/95 p-5 backdrop-blur"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#5a1bb0]">Product catalog</p><h2 id="product-modal-title" className="mt-1 text-xl font-black text-[#220046]">{editingId ? 'Edit product' : 'Add product'}</h2><p className="mt-1 text-sm text-slate-500">Prices and conversions are used by the POS and reports.</p></div><button aria-label="Close product form" className="rounded-lg p-2 text-[#4b2a7a] transition hover:bg-[#f5ebff]" onClick={closeProductModal} type="button">×</button></div><form className="space-y-4 p-5" onSubmit={submit}><ProductFormFields categories={data.categories} form={form} setField={setField} />{message && <Notice>{message}</Notice>}<div className="flex flex-wrap justify-end gap-2 border-t border-slate-100 pt-4"><Button type="button" variant="ghost" onClick={closeProductModal}>Cancel</Button><Button disabled={saving}>{saving ? 'Saving…' : editingId ? 'Save changes' : 'Add product'}</Button></div></form><form className="border-t border-slate-100 p-5" onSubmit={addNewCategory}><p className="text-sm font-semibold text-[#39235f]">Add a category</p><div className="mt-2 flex flex-col gap-2 sm:flex-row"><Input aria-label="New category name" placeholder="e.g. Ice cream" value={categoryName} onChange={(event) => setCategoryName(event.target.value)} /><Button type="submit">Add category</Button></div></form></section></div>}</>
}

function InventoryEntryForm({ mode, client, data, onRefresh, onError }: ScreenProps & { mode: 'receive' | 'adjust' }) {
  const [productId, setProductId] = useState('')
  const [quantity, setQuantity] = useState('')
  const [direction, setDirection] = useState<'add' | 'remove'>('add')
  const [reason, setReason] = useState(mode === 'receive' ? 'Stock delivery' : '')
  const [message, setMessage] = useState('')
  const [saving, setSaving] = useState(false)
  const stock = getStockByProduct(data.inventory)
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(''); const qty = Number(quantity); const product = data.products.find((item) => item.id === productId); const delta = mode === 'receive' || direction === 'add' ? qty : -qty; if (!product || !Number.isFinite(qty) || qty <= 0 || !reason.trim()) { setMessage('Select a product, enter a quantity greater than zero, and provide a reason.'); return } if (mode === 'adjust' && delta < 0 && (stock[product.id] ?? 0) + delta < 0) { setMessage('This adjustment would make stock negative.'); return } setSaving(true); try { await addInventoryEntry(client, { stall_id: data.stall?.id ?? '', product_id: product.id, quantity_delta: delta, movement_type: mode === 'receive' ? 'receive' : 'adjustment', reason: reason.trim() }); setQuantity(''); setMessage(`${mode === 'receive' ? 'Stock received' : 'Inventory adjusted'} successfully.`); await onRefresh() } catch (error) { onError(getErrorMessage(error)) } finally { setSaving(false) } }
  return <Panel title={mode === 'receive' ? 'Receive stock' : 'Adjust inventory'} description={mode === 'receive' ? 'Record deliveries as positive ledger entries.' : 'Correct stock counts while protecting against negative inventory.'}><form className="max-w-xl space-y-4" onSubmit={submit}><Select label="Product" value={productId} onChange={(event) => setProductId(event.target.value)} required><option value="">Choose a product</option>{data.products.filter((product) => product.is_sellable || mode === 'receive').map((product) => <option key={product.id} value={product.id}>{product.name} ({product.unit}) · on hand {(stock[product.id] ?? 0).toLocaleString()}</option>)}</Select>{mode === 'adjust' && <Select label="Adjustment direction" value={direction} onChange={(event) => setDirection(event.target.value as 'add' | 'remove')}><option value="add">Add stock</option><option value="remove">Remove stock</option></Select>}<Input label="Quantity" type="number" min="0.001" step="0.001" value={quantity} onChange={(event) => setQuantity(event.target.value)} required /><Textarea label="Reason" rows={3} placeholder="Supplier delivery, count correction, damaged stock…" value={reason} onChange={(event) => setReason(event.target.value)} required />{message && <Notice>{message}</Notice>}<Button disabled={saving}>{saving ? 'Saving…' : mode === 'receive' ? 'Record delivery' : 'Save adjustment'}</Button></form></Panel>
}

export function ReceivingScreen(props: ScreenProps) { return <InventoryEntryForm {...props} mode="receive" /> }
export function AdjustmentsScreen(props: ScreenProps) { return <InventoryEntryForm {...props} mode="adjust" /> }

export function PricingScreen({ client, data, onRefresh, onError }: ScreenProps) {
  const [drafts, setDrafts] = useState<Record<string, { sale_price: string; cost_price: string; pack_size: string; conversion_rate: string }>>({})
  const [savingId, setSavingId] = useState<string>()
  function draft(product: Product) { return drafts[product.id] ?? { sale_price: String(product.sale_price), cost_price: String(product.cost_price), pack_size: String(product.pack_size), conversion_rate: String(product.conversion_rate) } }
  async function save(product: Product) { const values = draft(product); const numbers = [values.sale_price, values.cost_price, values.pack_size, values.conversion_rate].map(Number); if (numbers.some((value) => !Number.isFinite(value) || value < 0) || numbers[2] <= 0 || numbers[3] <= 0) { onError('Enter valid prices and positive pack/conversion values.'); return } setSavingId(product.id); try { await saveProduct(client, { stall_id: product.stall_id, category_id: product.category_id, sku: product.sku, name: product.name, unit: product.unit, sale_price: numbers[0], cost_price: numbers[1], low_stock_threshold: product.low_stock_threshold, pack_size: numbers[2], conversion_rate: numbers[3], is_sellable: product.is_sellable }, product.id); await onRefresh() } catch (error) { onError(getErrorMessage(error)) } finally { setSavingId(undefined) } }
  return <Panel title="Price and conversion management" description="Update retail prices, raw costs, and pack-to-usable-unit conversions without an app release.">{data.products.length === 0 ? <EmptyState title="No products yet" description="Add products before changing their prices." /> : <Table><TableHead><th className="px-3 py-3">Product</th><th className="px-3 py-3">Sale price</th><th className="px-3 py-3">Cost price</th><th className="px-3 py-3">Pack size</th><th className="px-3 py-3">Usable units / pack</th><th className="px-3 py-3" /></TableHead><tbody>{data.products.map((product) => { const values = draft(product); const set = (field: keyof typeof values, value: string) => setDrafts((current) => ({ ...current, [product.id]: { ...values, [field]: value } })); return <tr key={product.id} className="border-b border-slate-100"><TableCell><p className="font-medium">{product.name}</p><p className="text-xs text-slate-400">{product.unit}</p></TableCell><TableCell><input className="w-28 rounded border border-slate-300 px-2 py-1" type="number" min="0" step="0.01" value={values.sale_price} onChange={(event) => set('sale_price', event.target.value)} /></TableCell><TableCell><input className="w-28 rounded border border-slate-300 px-2 py-1" type="number" min="0" step="0.01" value={values.cost_price} onChange={(event) => set('cost_price', event.target.value)} /></TableCell><TableCell><input className="w-24 rounded border border-slate-300 px-2 py-1" type="number" min="0.001" step="0.001" value={values.pack_size} onChange={(event) => set('pack_size', event.target.value)} /></TableCell><TableCell><input className="w-28 rounded border border-slate-300 px-2 py-1" type="number" min="0.001" step="0.001" value={values.conversion_rate} onChange={(event) => set('conversion_rate', event.target.value)} /></TableCell><TableCell><Button disabled={savingId === product.id} onClick={() => void save(product)}>{savingId === product.id ? 'Saving…' : 'Save'}</Button></TableCell></tr> })}</tbody></Table>}</Panel>
}

export function TransactionsScreen({ client, data, onRefresh, onError }: ScreenProps) {
  const [status, setStatus] = useState('all')
  const [search, setSearch] = useState('')
  const [selectedId, setSelectedId] = useState<string>()
  const [reason, setReason] = useState('Customer changed mind')
  const [restock, setRestock] = useState(true)
  const filtered = data.transactions.filter((transaction) => (status === 'all' || transaction.status === status) && transaction.receipt_number.toLowerCase().includes(search.toLowerCase()))
  async function reverse() { if (!selectedId || !reason.trim()) return; try { await reverseTransaction(client, selectedId, reason.trim(), restock); setSelectedId(undefined); await onRefresh() } catch (error) { onError(getErrorMessage(error)) } }
  return <Panel title="Transaction history" description="Review sales and reverse an eligible transaction with an audit reason." action={<div className="flex gap-2"><Input aria-label="Search receipts" placeholder="Receipt number" value={search} onChange={(event) => setSearch(event.target.value)} /><Select aria-label="Filter status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="completed">Completed</option><option value="voided">Voided</option><option value="refunded">Refunded</option></Select></div>}>{filtered.length === 0 ? <EmptyState title="No transactions found" description="Sales will appear here after the POS syncs them." /> : <Table><TableHead><th className="px-3 py-3">Receipt</th><th className="px-3 py-3">Date</th><th className="px-3 py-3">Total</th><th className="px-3 py-3">Status</th><th className="px-3 py-3" /></TableHead><tbody>{filtered.map((transaction) => <tr key={transaction.id} className="border-b border-slate-100"><TableCell className="font-medium">{transaction.receipt_number}</TableCell><TableCell>{dateTime.format(new Date(transaction.occurred_at))}</TableCell><TableCell>{peso.format(transaction.total_amount)}</TableCell><TableCell><Badge tone={transaction.status === 'completed' ? 'success' : transaction.status === 'voided' ? 'danger' : 'warning'}>{transaction.status}</Badge></TableCell><TableCell>{transaction.status === 'completed' && <Button variant="danger" onClick={() => setSelectedId(transaction.id)}>Void / reverse</Button>}</TableCell></tr>)}</tbody></Table>}{selectedId && <div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4"><p className="font-semibold text-red-800">Reverse transaction</p><p className="mt-1 text-sm text-red-700">Choose whether the sold stock should return to inventory.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><Select label="Reason" value={reason} onChange={(event) => setReason(event.target.value)}><option>Customer changed mind</option><option>Incorrect order</option><option>Quality issue</option></Select><Select label="Stock action" value={restock ? 'restock' : 'waste'} onChange={(event) => setRestock(event.target.value === 'restock')}><option value="restock">Restock items</option><option value="waste">Waste stock</option></Select></div><div className="mt-3 flex gap-2"><Button variant="danger" onClick={() => void reverse()}>Confirm reversal</Button><Button variant="ghost" onClick={() => setSelectedId(undefined)}>Cancel</Button></div></div>}</Panel>
}

export function ReportsScreen({ data }: ScreenProps) {
  const [from, setFrom] = useState(new Date(Date.now() - 6 * 86400000).toISOString().slice(0, 10))
  const [to, setTo] = useState(new Date().toISOString().slice(0, 10))
  const report = useMemo(() => { const transactions = data.transactions.filter((transaction) => { const date = transaction.occurred_at.slice(0, 10); return date >= from && date <= to }); const completed = transactions.filter((transaction) => transaction.status === 'completed'); const voided = transactions.filter((transaction) => transaction.status === 'voided'); const itemTotals = data.transactionItems.filter((item) => completed.some((transaction) => transaction.id === item.transaction_id)).reduce<Record<string, number>>((totals, item) => { totals[item.product_name] = (totals[item.product_name] ?? 0) + item.quantity; return totals }, {}); return { transactions, completed, voided, sales: completed.reduce((sum, transaction) => sum + transaction.total_amount, 0), itemTotals } }, [data, from, to])
  function exportReport() { downloadCsv(`sales-report-${from}-to-${to}.csv`, report.transactions.map((transaction) => ({ receipt: transaction.receipt_number, occurred_at: transaction.occurred_at, status: transaction.status, subtotal: transaction.subtotal, total: transaction.total_amount, cash_received: transaction.cash_received, change: transaction.change_amount }))) }
  return <div className="space-y-6"><Panel title="Sales reporting" description="Filter the reporting window, then export the exact rows shown." action={<div className="flex flex-wrap gap-2"><Input label="From" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /><Input label="To" type="date" value={to} onChange={(event) => setTo(event.target.value)} /><Button className="self-end" onClick={exportReport} disabled={report.transactions.length === 0}>Download CSV</Button></div>}><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-[#f4ecff] p-4"><p className="text-sm text-[#5a1bb0]">Net completed sales</p><p className="mt-2 text-2xl font-bold text-[#220046]">{peso.format(report.sales)}</p></div><div className="rounded-xl bg-slate-100 p-4"><p className="text-sm text-slate-600">Completed transactions</p><p className="mt-2 text-2xl font-bold">{report.completed.length}</p></div><div className="rounded-xl bg-amber-50 p-4"><p className="text-sm text-amber-700">Voided transactions</p><p className="mt-2 text-2xl font-bold text-amber-900">{report.voided.length}</p></div></div></Panel><Panel title="Units sold" description="Based on transaction items attached to completed sales.">{Object.keys(report.itemTotals).length === 0 ? <EmptyState title="No item data in this period" description="Completed sales with line items will appear here." /> : <Table><TableHead><th className="px-3 py-3">Product</th><th className="px-3 py-3">Quantity sold</th></TableHead><tbody>{Object.entries(report.itemTotals).sort(([, a], [, b]) => b - a).map(([name, quantity]) => <tr key={name} className="border-b border-slate-100"><TableCell>{name}</TableCell><TableCell>{quantity.toLocaleString()}</TableCell></tr>)}</tbody></Table>}</Panel></div>
}
